kind: Pod
apiVersion: v1
metadata:
  name: myfirstpod
spec:
  containers:
  - name: container1
    image: aamirpinger/helloworld:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80