apiVersion: v1
kind: Pod
metadata:
  name: podwithlabels
  labels:
    type: backend
    phase: production
spec:
  containers:
  - name: container1
    image: aamirpinger/helloworld:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80