kind: Pod
apiVersion: v1
metadata:
  name: podwithlabels
  labels:
    type: backend
    phase: production
spec:
  containers:
  - image: aamirpinger/helloworld:latest
    name: container1
    ports:
    - containerPort: 80